### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) to leverage / use services and information that are exclusively available to registered users. 

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#1]
- [ ] Upon successful registration, the *menu* screen appears, and the user is logged in.
- [ ] Upon failure, an error is displayed, and the user is redirected to the login screen.
- [ ] Logged-in users can log out and log back into their registered profile.

Development Tasks:
- [x] sopra-fs22-group-13/braendi-dog-client#27
- [x] sopra-fs22-group-13/braendi-dog-server#60
- [x] sopra-fs22-group-13/braendi-dog-server#61
- [x] sopra-fs22-group-13/braendi-dog-server#62

**Comment by shzeng** [comment]
Development Tasks

- [ ] Implement User Page that makes a Post request to /login
- [ ] Implement user data base
- [ ] Implement Rest Controller
- [ ] Create registration logic in Rest service
