### ISSUE TITLE
As a user I want the website to update correctly if I leave it so that I can quickly close it without further complications

### ISSUE THREAD

**Issue by LucaZwahlen** [sopra-fs22-group-13/braendi-dog-server#104]
- [ ] Leaving from the Lobby page should throw me out of the lobby
- [ ] Leaving from the Game page should throw me out of the game and close the game for the others

Development Tasks

- [x] sopra-fs22-group-13/braendi-dog-server#121
- [x] sopra-fs22-group-13/braendi-dog-client#53
- [x] sopra-fs22-group-13/braendi-dog-server#123
- [x] sopra-fs22-group-13/braendi-dog-server#124
- [x] sopra-fs22-group-13/braendi-dog-server#125
