### ISSUE TITLE
As a Player I want to see what cards the others played so that I can better understand what is going on in the game

### ISSUE THREAD

**Issue by LucaZwahlen** [sopra-fs22-group-13/braendi-dog-server#105]
- [ ] After a move, all players should see the just played card
- [ ] Only the last played card is visible

Development Tasks

- [x] sopra-fs22-group-13/braendi-dog-client#55
- [x] sopra-fs22-group-13/braendi-dog-server#133
- [x] sopra-fs22-group-13/braendi-dog-client#56
