### ISSUE TITLE
As a player I want to see the general state of the dog board so that I see what moves make sense for me next.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#13]
- [ ] The Dog Board is displayed at all times while in the game
- [ ] When a player completes a move, the board is updated and the new state of the board is shown.
- [ ] The Dog Board is oriented such that my color is facing towards me.

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#15
- [x] sopra-fs22-group-13/braendi-dog-client#29
- [x] sopra-fs22-group-13/braendi-dog-server#53
- [x] sopra-fs22-group-13/braendi-dog-server#54
- [x] sopra-fs22-group-13/braendi-dog-server#78
