### ISSUE TITLE
As a player I want to see the number of cards all other players have so that I can see if someone cannot play.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#14]
- [ ] All players cards are shown at all times.
- [ ] When a player completes a move, his card amount is updated to show the new number of cards
- [ ] The card faces of other players are not visible to me

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#17
- [x] sopra-fs22-group-13/braendi-dog-client#18
- [x] sopra-fs22-group-13/braendi-dog-server#58
