### ISSUE TITLE
As a player I want to be able to use the voice chat so I can talk with the other players in the lobby.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#15]
- [ ] At the  start of the game all four players in this game join the voice call automatically.
- [ ] If the voice call does not work everybody is alerted.
- [ ] It is possible to directly talk with all other players in real-time.

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-server#29
- [x] sopra-fs22-group-13/braendi-dog-client#19
- [x] sopra-fs22-group-13/braendi-dog-server#31
