### ISSUE TITLE
As a player I want to be able to mute myself and adjust the output volume of every player to regulate the voice chat output.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#16]
- [ ] Players can mute themselves.
- [ ] Every player's output volume can be set.

Development Tasks

- [x] sopra-fs22-group-13/braendi-dog-client#44
- [x] sopra-fs22-group-13/braendi-dog-client#43
- [x] sopra-fs22-group-13/braendi-dog-client#42
