### ISSUE TITLE
As a player after starting the round, I want to have access to the game field and be handed cards so the round can get started.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#17]
- [ ] The Dog Board is shown after loading the game.
- [ ] Every player in the game gets their starting cards upon loading into the game.
- [ ] The game starts automatically once the cards are handed out.

Development tasks:

- [x] sopra-fs22-group-13/braendi-dog-server#35
- [x] sopra-fs22-group-13/braendi-dog-client#30
- [x] sopra-fs22-group-13/braendi-dog-server#37
- [x] sopra-fs22-group-13/braendi-dog-client#20
- [x] sopra-fs22-group-13/braendi-dog-client#21
- [x] sopra-fs22-group-13/braendi-dog-client#22
- [x] sopra-fs22-group-13/braendi-dog-client#23
