### ISSUE TITLE
As a player I want to see which player and which corresponding team won. So I can see the result of the game.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#19]
- [ ] When a player wins, the game stops and you are redirected to the *menu*
- [ ] The winner is shown to all players.
- [ ] The winner's team member is shown to all players

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#25
- [x] sopra-fs22-group-13/braendi-dog-client#26
- [x] sopra-fs22-group-13/braendi-dog-server#24
