### ISSUE TITLE
As a logged-in user I want to access and see the lobby and profile services and information in a centralized location so that I can start using their functionalities.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#5]
- [ ] A user must be logged in, in order to see the *menu*
- [ ] A user can log out from the *menu* by clicking the logout button
- [ ] The *lobby* and *profile page* can be controlled through the menu by navigating in their respective windows
- [ ] Upon leaving the lobby, the game or the profile page, the user should be redirected to the *menu*.
- [ ] The menu displays pending invites

Developments Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#3
- [x] sopra-fs22-group-13/braendi-dog-server#75
- [x] sopra-fs22-group-13/braendi-dog-client#4
