### ISSUE TITLE
As a registered and logged in user, I want to be able to create a lobby so I can invite three other users to play with. 

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#6]
- [ ] A user can send invitations to other users based on their username.
- [ ] An invited user can join the lobby by clicking on a "join" button.
- [ ] Upon successfully joining, the *lobby overview* is shown, and the user is automatically in the lobby.
- [ ] Upon failure, an error is displayed and nothing else changes. A joining error can be that the lobby filled up moment before trying to join.
- [ ] A user that joined can also leave the lobby again.
- [ ] Only logged-in users can join lobbies.

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#5
- [x] sopra-fs22-group-13/braendi-dog-server#67
- [x] sopra-fs22-group-13/braendi-dog-client#6
- [x] sopra-fs22-group-13/braendi-dog-server#69
- [x] sopra-fs22-group-13/braendi-dog-server#71
- [x] sopra-fs22-group-13/braendi-dog-server#70
- [x] sopra-fs22-group-13/braendi-dog-server#72
- [x] sopra-fs22-group-13/braendi-dog-server#73
