### ISSUE TITLE
As a player I want to be able to play a card from my hand to initiate my turn.

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#8]
- [ ] The cards in my hands are clickable, resulting in it being played.
- [ ] When it's not the player's turn, cards can't be played.
- [ ] After playing the card, it should be highlighted in the hand.
- [ ] After playing a card the player's marble on the board becomes clickable.

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#7
- [x] sopra-fs22-group-13/braendi-dog-client#8
- [x] sopra-fs22-group-13/braendi-dog-client#9
