### ISSUE TITLE
As a player, after I have played a card, I want to be able to move a marble on the board to finish my turn

### ISSUE THREAD

**Issue by shzeng** [sopra-fs22-group-13/braendi-dog-server#9]
- [ ] After clicking a marble, it is highlighted and the player can pick a field to move to.
- [ ] Marbles can be deselected by clicking on them again.
- [ ] If the selected field is not reachable given the game's rules, an error is shown, and the player again needs to select a card. The previously selected card is not used.
- [ ] If the field can be reached, given the played card and the rules, the marbles is moved to the selected field.
- [ ] If the selected was not a 7, after moving a marble, the turn is ended.
- [ ] If the selected card was a 7, after moving a marble, the marbles stay clickable and the move is ended when the move distances sum up to 7.
- [ ] The players card is removed from the hand and becomes visible for all players until the end of the next turn.

Development Tasks:

- [x] sopra-fs22-group-13/braendi-dog-client#11
- [x] sopra-fs22-group-13/braendi-dog-client#12
- [x] sopra-fs22-group-13/braendi-dog-client#13
- [x] sopra-fs22-group-13/braendi-dog-server#46
- [x] sopra-fs22-group-13/braendi-dog-server#47
- [x] sopra-fs22-group-13/braendi-dog-server#48
- [x] sopra-fs22-group-13/braendi-dog-server#49
- [x] sopra-fs22-group-13/braendi-dog-server#50
